# Generated by Django 4.1.6 on 2023-02-09 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalCost', models.CharField(max_length=20)),
                ('ProductInfo', models.CharField(max_length=400)),
                ('Finished', models.IntegerField(default=0)),
                ('OrderDate', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, unique=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Manufacturer', models.CharField(max_length=30)),
                ('Length', models.CharField(max_length=20)),
                ('Cost', models.CharField(max_length=10)),
                ('Stock', models.BigIntegerField()),
                ('Description', models.CharField(max_length=500, null=True)),
                ('Contact', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('sex', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('totalcost', models.IntegerField(default=0)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.userperson')),
                ('Finalorder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Inventory.finalorder')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.product')),
            ],
        ),
    ]
