# Generated by Django 4.1.6 on 2023-02-23 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShipperName', models.CharField(max_length=30)),
                ('OceanVessel', models.CharField(max_length=50)),
                ('LocalVessel', models.CharField(max_length=50, null=True)),
                ('LocalVesselOrigin', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BL', models.CharField(max_length=20, unique=True)),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('PortDischarge', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FinalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalCost', models.IntegerField(default=0)),
                ('ProductInfo', models.CharField(max_length=400)),
                ('Finished', models.IntegerField(default=0)),
                ('OrderDate', models.DateField(auto_now_add=True)),
                ('Number', models.IntegerField(default=None, unique=True)),
                ('Place', models.CharField(default=None, max_length=70)),
                ('NumOfBL', models.IntegerField(default=3)),
                ('PayAt', models.CharField(default=None, max_length=70, null=True)),
                ('PlaceDate', models.CharField(default=None, max_length=100)),
                ('FreightsCharges', models.FloatField(default=None, null=True)),
                ('RevTons', models.CharField(default=None, max_length=1000, null=True)),
                ('Rate', models.FloatField(default=None, null=True)),
                ('Prepaid', models.CharField(default=None, max_length=70)),
                ('Collect', models.CharField(default=None, max_length=70)),
                ('Portload', models.CharField(default=None, max_length=255)),
                ('Portdis', models.CharField(default=None, max_length=255)),
                ('TranshTo', models.CharField(default=None, max_length=50, null=True)),
                ('FinalDest', models.CharField(default=None, max_length=255, null=True)),
                ('Verification', models.CharField(default='', max_length=13, unique=True)),
                ('BL', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Inventory.consignee', to_field='BL')),
            ],
        ),
        migrations.CreateModel(
            name='NotifyParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Street', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Image', models.ImageField(blank=True, default='N/A', null=True, upload_to='images/')),
                ('Manufacturer', models.CharField(default=None, max_length=100)),
                ('ManuLoc', models.CharField(default=None, max_length=255)),
                ('Color', models.CharField(default=None, max_length=20)),
                ('Measurement', models.CharField(default=None, max_length=30)),
                ('GrossWeight', models.CharField(default=None, max_length=40)),
                ('Marks', models.CharField(default=None, max_length=300, null=True)),
                ('Length', models.CharField(max_length=20)),
                ('Cost', models.CharField(max_length=10)),
                ('Stock', models.BigIntegerField(default=0)),
                ('Description', models.CharField(max_length=500)),
                ('Contact', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Userperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('sex', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('totalcost', models.IntegerField(default=0)),
                ('BL', models.CharField(default=True, max_length=20, unique=True)),
                ('Voyage', models.IntegerField(default=0)),
                ('Marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.product')),
                ('Verificaton', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Inventory.finalorder', to_field='Verification')),
            ],
        ),
        migrations.AddField(
            model_name='finalorder',
            name='Marks',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Inventory.product'),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='NotifyName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Inventory.notifyparty', to_field='Name'),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='Shipper',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Inventory.company'),
        ),
    ]
