# Generated by Django 4.1.6 on 2023-02-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='OrderID',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='OrderDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
