# Generated by Django 4.1.6 on 2023-02-09 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='Finished',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='Finalorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Inventory.finalorder'),
        ),
    ]
