# Generated by Django 4.1.6 on 2023-02-23 17:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalorder',
            name='Marks',
        ),
        migrations.RemoveField(
            model_name='finalorder',
            name='Number',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='BL',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='Voyage',
        ),
        migrations.AddField(
            model_name='finalorder',
            name='Charges',
            field=models.FloatField(default=None, max_length=11, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='Voyage',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='OrderedProductID',
            field=models.CharField(default=None, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='BL',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='NotifyName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Inventory.notifyparty'),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='NumOfBL',
            field=models.IntegerField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Prepaid',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Rate',
            field=models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Verification',
            field=models.CharField(default=None, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='Verificaton',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Inventory.finalorder'),
        ),
    ]
