# Generated by Django 4.1.6 on 2023-02-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_orderedproduct_finalorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='Client',
        ),
    ]
