# Generated by Django 4.1.6 on 2023-02-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='Place',
            field=models.CharField(default='Kaohsiung, Taiwan', max_length=70),
        ),
    ]
