# Generated by Django 4.1.6 on 2023-02-07 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_orderedproduct_quantity_orderedproduct_totalcost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Color',
            new_name='Length',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Brand',
            new_name='Manufacturer',
        ),
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='FinalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Products', models.CharField(max_length=500)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.userperson')),
            ],
        ),
    ]
