# Generated by Django 4.1.6 on 2023-02-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_remove_orderedproduct_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='TotalCost',
            field=models.IntegerField(default=0),
        ),
    ]
