# Generated by Django 4.1.6 on 2023-02-24 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_alter_finalorder_bl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='BL',
            field=models.CharField(blank=True, default=None, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='FinalDest',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='NotifyName',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Inventory.notifyparty'),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='PayAt',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Portdis',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Portload',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Prepaid',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Shipper',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Inventory.company'),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='TranshTo',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Verification',
            field=models.CharField(blank=True, default=None, max_length=13, unique=True),
        ),
    ]
