# Generated by Django 4.1.6 on 2023-02-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_rename_color_product_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Contact',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
