# Generated by Django 4.1.6 on 2023-02-24 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_alter_finalorder_bl_alter_finalorder_finaldest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='Charges',
            field=models.FloatField(blank=True, default=None, max_length=11, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='FinalDest',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='NumOfBL',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='PayAt',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Portdis',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Portload',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Prepaid',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='RevTons',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='TranshTo',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Voyage',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
