# Generated by Django 4.1.6 on 2023-02-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_rename_verificaton_orderedproduct_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='PlaceDate',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
