# Generated by Django 4.1.6 on 2023-02-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0015_alter_finalorder_bl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignee',
            name='BL',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
