# Generated by Django 4.1.6 on 2023-02-24 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0016_alter_consignee_bl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='BL',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.consignee'),
        ),
    ]
