# Generated by Django 4.1.6 on 2023-02-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0017_alter_finalorder_bl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignee',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
