# Generated by Django 4.1.6 on 2023-03-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0019_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
