# Generated by Django 4.1.6 on 2023-03-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0020_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='Finished',
            field=models.BooleanField(default=False),
        ),
    ]
