# Generated by Django 4.1.6 on 2023-03-20 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0021_alter_finalorder_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='ProductInfo',
            field=models.CharField(blank=True, default=None, max_length=400),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Rate',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, default='/pics/defproduct.jpg', null=True, upload_to='images/'),
        ),
    ]
