# Generated by Django 4.1.6 on 2023-03-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0022_alter_finalorder_productinfo_alter_finalorder_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, default='static/pics/defproduct.jpg', null=True, upload_to='images/'),
        ),
    ]
