# Generated by Django 4.1.6 on 2023-03-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0023_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, default='static/pic/defproduct.jpg', null=True, upload_to='images/'),
        ),
    ]
