# Generated by Django 4.1.6 on 2023-03-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0030_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='TotalCost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='totalcost',
            field=models.FloatField(default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='Cost',
            field=models.FloatField(default=0, max_length=7),
        ),
    ]
