# Generated by Django 4.1.6 on 2023-03-20 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0031_alter_finalorder_totalcost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='ProductInfo',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='RevTons',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='TotalCost',
            field=models.FloatField(default=0, max_length=12, validators=[django.core.validators.DecimalValidator(10, 2)]),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Verification',
            field=models.CharField(blank=True, default='', max_length=13, null=True, unique=True),
        ),
    ]
