# Generated by Django 4.1.6 on 2023-03-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0032_alter_finalorder_productinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='TotalCost',
            field=models.FloatField(default=0, max_length=12),
        ),
    ]
