# Generated by Django 4.1.6 on 2023-03-21 04:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0034_alter_finalorder_totalcost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='Charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, max_length=11, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='TotalCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.DecimalValidator(10, 2)]),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='totalcost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.DecimalValidator(10, 2)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.DecimalValidator(5, 2)]),
        ),
    ]
