# Generated by Django 4.1.6 on 2023-03-27 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0035_alter_finalorder_charges_alter_finalorder_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignee',
            name='PortDischarge',
        ),
    ]
