# Generated by Django 4.1.6 on 2023-03-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0036_remove_consignee_portdischarge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='Shipper',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
