# Generated by Django 4.1.6 on 2023-03-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0037_alter_finalorder_shipper_delete_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='Shipper',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
