# Generated by Django 4.1.6 on 2023-03-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0038_alter_finalorder_shipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='LocalVessel',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='LocalVesselOrigin',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='OceanVessel',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='ShipperName',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
