# Generated by Django 4.1.6 on 2023-03-27 12:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0039_finalorder_localvessel_finalorder_localvesselorigin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='Charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, max_length=11, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
