# Generated by Django 4.1.6 on 2023-03-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0040_alter_finalorder_charges_alter_finalorder_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalorder',
            name='Shipper',
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='ShipperName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
