# Generated by Django 4.1.6 on 2023-03-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0041_remove_finalorder_shipper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalorder',
            name='ProductInfo',
        ),
    ]
