# Generated by Django 4.1.6 on 2023-04-01 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0042_remove_finalorder_productinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.DecimalValidator(7, 2)]),
        ),
    ]
