# Generated by Django 4.1.6 on 2023-04-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0044_finalorder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='Time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
