# Generated by Django 4.1.6 on 2023-04-02 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0045_alter_finalorder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
