# Generated by Django 4.1.6 on 2023-04-02 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0047_alter_finalorder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 2, 13, 25, 57, 992771, tzinfo=datetime.timezone.utc)),
        ),
    ]
