# Generated by Django 4.1.6 on 2023-04-15 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0048_alter_finalorder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 15, 5, 11, 2, 554285, tzinfo=datetime.timezone.utc)),
        ),
    ]
