# Generated by Django 4.1.6 on 2023-04-15 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0049_alter_finalorder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 15, 7, 32, 39, 680801, tzinfo=datetime.timezone.utc)),
        ),
    ]
