# Generated by Django 4.1.6 on 2023-04-23 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0050_alter_finalorder_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalorder',
            name='LocalVessel',
        ),
        migrations.RemoveField(
            model_name='finalorder',
            name='LocalVesselOrigin',
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 23, 11, 24, 51, 685501, tzinfo=datetime.timezone.utc)),
        ),
    ]
