# Generated by Django 4.1.6 on 2023-05-03 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0051_remove_finalorder_localvessel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 3, 18, 24, 55, 663164, tzinfo=datetime.timezone.utc)),
        ),
    ]
