# Generated by Django 4.1.6 on 2023-05-03 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0052_alter_finalorder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 3, 18, 28, 14, 251847, tzinfo=datetime.timezone.utc)),
        ),
    ]
