# Generated by Django 4.1.6 on 2023-05-07 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0054_alter_finalorder_time_alter_product_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='PayAt',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Place',
            field=models.CharField(default='Kaohsiung, Taiwan', max_length=255),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 7, 14, 1, 53, 774006, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='TranshTo',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
