# Generated by Django 4.1.6 on 2023-05-10 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0055_alter_finalorder_payat_alter_finalorder_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='OceanVessel',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 10, 15, 45, 33, 442793, tzinfo=datetime.timezone.utc)),
        ),
    ]
