# Generated by Django 4.1.6 on 2023-05-10 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0058_remove_product_color_alter_finalorder_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 10, 16, 52, 25, 216919, tzinfo=datetime.timezone.utc)),
        ),
    ]
