# Generated by Django 4.1.6 on 2023-05-10 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0059_product_available_alter_finalorder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 10, 17, 58, 38, 239196, tzinfo=datetime.timezone.utc)),
        ),
    ]
