# Generated by Django 4.1.6 on 2023-05-10 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0060_alter_finalorder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 10, 19, 10, 1, 448496, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='Voyage',
            field=models.CharField(default='', max_length=255),
        ),
    ]
