# Generated by Django 4.1.6 on 2023-07-20 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0063_alter_finalorder_time_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 7, 20, 10, 58, 1, 977509, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
