# Generated by Django 4.1.6 on 2023-07-20 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0065_alter_finalorder_time_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 7, 20, 11, 55, 33, 532105, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='GrossWeight',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='Length',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='ManuLoc',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='Manufacturer',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='Measurement',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
